### ISSUE TITLE
Website doesn't work

### ISSUE THREAD

**Issue by KristjanESPERANTO** [EqualStreetNames/equalstreetnames-halle-saale#3]
404 Error on https://halle-saale.equalstreetnames.eu/

**Comment by jbelien** [comment]
Back online: https://halle-saale.equalstreetnames.eu/

**Comment by hjoertel** [comment]
Am Donnerstag, 18. Mai 2023, 11:53:03 CEST schrieb Jonathan Beliën:
> Back online: https://halle-saale.equalstreetnames.eu/

Danke!
-- 
mit freundlichen Grüßen aus Halle (Saale)
       Heinz-Jürgen Oertel
